version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.16
    container_name: ***REMOVED***-consul
    volumes:
      - .***REMOVED***-state/consul:/consul/data
    networks:
      - ***REMOVED***-net
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: 'agent -server -bootstrap-expect=1 -ui -client=0.0.0.0'

  ***REMOVED***-control:
    build:
      context: .
    container_name: ***REMOVED***-control
    volumes:
      - .:/***REMOVED***
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - DEBUG=${DEBUG:-false}
    networks:
      - ***REMOVED***-net
    depends_on:
      - consul

  dashboard:
    image: b4bz/homer:latest
    container_name: ***REMOVED***-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./dashboard:/www
    environment:
      - INIT_ASSETS=0
    networks:
      - ***REMOVED***-net
    depends_on:
      - ***REMOVED***-control

networks:
  ***REMOVED***-net:
    name: ***REMOVED***-net