version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    volumes:
      - consul_data:/consul/data
    networks:
      - ***REMOVED***
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -bootstrap -ui -client=0.0.0.0

  control:
    build:
      context: .
    container_name: control
    volumes:
      - .:/***REMOVED***
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro
    ports:
      - "3000:3000"  # FastAPI server
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - DEBUG=${DEBUG:-false}
    networks:
      - ***REMOVED***
    depends_on:
      - consul
    command: python cli/api.py

networks:
  ***REMOVED***:
    name: ***REMOVED***

volumes:
  consul_data: