version: '3.8'

services:
  consul:
    image: progrium/consul:latest
    container_name: ***REMOVED***-consul
    volumes:
      - ${STORAGE_TYPE:-.***REMOVED***-state}/consul:/consul/data
    networks:
      - ***REMOVED***-net
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: -server -bootstrap -ui-dir /ui

  ***REMOVED***-control:
    build:
      context: .
    container_name: ***REMOVED***-control
    volumes:
      - .:/***REMOVED***
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - DEBUG=${DEBUG:-false}
    networks:
      - ***REMOVED***-net
    depends_on:
      - consul

  dashboard:
    image: b4bz/homer:latest
    container_name: ***REMOVED***-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./dashboard/assets:/www/assets
      - ./dashboard/config.yml:/www/config.yml
    environment:
      - INIT_ASSETS=0  # Don't overwrite our custom assets
    networks:
      - ***REMOVED***-net
    depends_on:
      - ***REMOVED***-control
      - consul

networks:
  ***REMOVED***-net:
    name: ***REMOVED***-net