version: '3.8'

services:
  consul:  # Back to single node
    build:
      context: ./docker/consul
    container_name: consul
    volumes:
      - ./docker/consul:/consul  # Mount the consul directory
      - ./docker/consul/config.hcl.tpl:/consul/config/config.hcl.tpl:ro
    networks:
      - aini
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_DATA_DIR=/consul/data  # Update path
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
      - APP_SERVER_TYPE=${APP_SERVER_TYPE:-cx11}
      - GPU_SERVER_TYPE=${GPU_SERVER_TYPE:-ccx12}
      - DEBUG=${DEBUG:-false}
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

  control:
    build:
      context: .
    container_name: control
    volumes:
      - .:/aini  # This should include cli/static
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro
    ports:
      - "3000:3000"  # FastAPI server
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - HCLOUD_TOKEN=${HCLOUD_TOKEN}
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - DEBUG=${DEBUG:-false}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - AWS_DEFAULT_REGION=${S3_REGION}
    networks:
      - aini
    depends_on:
      - consul

networks:
  aini:
    name: aini

volumes:
  consul_data: