
# ansible/roles/hetzner/storage/tasks/create.yml
---
- name: Verify required variables
  assert:
    that:
      - hcloud_token != ""
      - bucket_name != ""
    fail_msg: "Missing required variables. Ensure HCLOUD_TOKEN and S3_BUCKET are set"

- name: Create S3 bucket
  uri:
    url: "https://api.hetzner.cloud/v1/object_storages"
    method: POST
    headers:
      Authorization: "Bearer {{ hcloud_token }}"
    body_format: json
    body:
      name: "{{ bucket_name }}"
      location: "{{ location }}"
    status_code: [200, 201, 409]
  register: storage_result

- name: Get access credentials
  uri:
    url: "https://api.hetzner.cloud/v1/object_storage_keys"
    method: POST
    headers:
      Authorization: "Bearer {{ hcloud_token }}"
    body_format: json
    body:
      name: "***REMOVED***-storage-key"
    status_code: [200, 201]
  register: credentials
  when: storage_result.status == 201

- name: Save credentials to file
  copy:
    content: |
      S3_ACCESS_KEY={{ credentials.json.access_key }}
      S3_SECRET_KEY={{ credentials.json.secret_key }}
      S3_BUCKET={{ bucket_name }}
      S3_ENDPOINT=https://{{ location }}.hetzner.com
      S3_REGION={{ location }}
    dest: "{{ credentials_file }}"
    mode: '0600'
  when: storage_result.status == 201