- name: Load common variables
  include_vars:
    dir: "{{ item }}"
    extensions: 
      - yml
      - yaml
    files_matching: "^.*\\.(yml|yaml)$"
  with_items:
    - "../../defaults"
    - "../../vars/common"
    - "../../vars/{{ lookup('env', 'DEPLOY_ENV') | default('dev2') }}"