# ansible/roles/common/consul/defaults/main.yml
---
consul_version: "1.16.0"
consul_datacenter: "dc1"
consul_domain: "consul"
consul_data_dir: "/opt/consul"
consul_config_dir: "/etc/consul.d"
consul_http_port: 8500
consul_dns_port: 8600
consul_encrypt_key: "" # Should be overridden in vault
consul_retry_join: []
consul_acl_enabled: true
consul_acl_default_policy: "deny"
consul_ui_enabled: true
