# ansible/roles/common/consul/defaults/main.yml
---
consul_version: "1.16.0"
consul_datacenter: "dc1"
consul_domain: "consul"
consul_data_dir: "/opt/consul"
consul_config_dir: "/etc/consul.d"
consul_http_port: 8500
consul_dns_port: 8600
consul_encrypt_key: "" # Should be overridden in vault
consul_retry_join: []
consul_acl_enabled: true
consul_acl_default_policy: "deny"
consul_ui_enabled: true

# ansible/roles/common/consul/tasks/main.yml
---
- name: Include installation tasks
  include_tasks: install.yml

- name: Include configuration tasks
  include_tasks: configure.yml

# ansible/roles/common/consul/tasks/install.yml
---
- name: Create Consul directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: Copy Consul configuration
  template:
    src: consul.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    mode: '0640'
  notify: restart consul

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ consul_config_dir }}/docker-compose.yml"
    mode: '0640'
  notify: restart consul

# ansible/roles/common/consul/templates/docker-compose.yml.j2
---
version: '3.8'

services:
  consul:
    image: hashicorp/consul:${CONSUL_VERSION:-1.16.0}
    container_name: consul
    restart: unless-stopped
    volumes:
      - ${CONSUL_DATA_DIR:-/opt/consul}:/consul/data
      - ${CONSUL_CONFIG_DIR:-/etc/consul.d}:/consul/config
    ports:
      - "${CONSUL_HTTP_PORT:-8500}:8500"
      - "${CONSUL_DNS_PORT:-8600}:8600/tcp"
      - "${CONSUL_DNS_PORT:-8600}:8600/udp"
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=true
    command: >
      agent -server -ui
      -bootstrap-expect=1
      -client=0.0.0.0
      -datacenter=${CONSUL_DATACENTER:-dc1}
      -domain=${CONSUL_DOMAIN:-consul}
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

# ansible/roles/common/consul/templates/consul.hcl.j2
datacenter = "{{ consul_datacenter }}"
data_dir = "{{ consul_data_dir }}"
client_addr = "0.0.0.0"
ui = {{ consul_ui_enabled | lower }}

server = true
bootstrap_expect = 1

acl {
  enabled = {{ consul_acl_enabled | lower }}
  default_policy = "{{ consul_acl_default_policy }}"
  enable_token_persistence = true
}

encrypt = "{{ consul_encrypt_key }}"

ports {
  http = {{ consul_http_port }}
  dns = {{ consul_dns_port }}
}

telemetry {
  disable_hostname = true
  prometheus_retention_time = "24h"
}