---
- name: Generate new keys
  block:
    - name: Ensure keys directory exists
      file:
        path: "{{ playbook_dir }}/../keys"
        state: directory
        mode: '0700'

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/../keys/app_server"
        type: "{{ ssh_key_type | default('ed25519') }}"
        size: "{{ ssh_key_size | default(4096) }}"
        state: present
        force: false
        regenerate: never
      register: ssh_key_gen

    - name: Read private key
      slurp:
        src: "{{ playbook_dir }}/../keys/app_server"
      register: secret_private_key_content

    - name: Save keys to vault file
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/../vars/dev2/secret_ssh_keys.yml"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      with_items:
        - regexp: "^vault_ssh_key_private:"
          line: "vault_ssh_key_private: '{{ secret_private_key_content.content | b64decode }}'"
        - regexp: "^vault_ssh_key_public:"
          line: "vault_ssh_key_public: '{{ ssh_key_gen.public_key }}'"

    - name: Clean up keys directory
      file:
        path: "{{ playbook_dir }}/../keys"
        state: absent

    - name: Reload SSH key variables
      include_vars:
        file: "{{ playbook_dir }}/../vars/dev2/secret_ssh_keys.yml"

  when: vault_ssh_key_private is not defined or vault_ssh_key_private == "" or vault_ssh_key_public is not defined or vault_ssh_key_public == "" 