---
# Cloud Provider Configuration
hetzner_token: "***REMOVED***"

# S3 Configuration
s3_access_key: "***REMOVED***"
s3_secret_key: "***REMOVED***Y"

# Traefik Configuration
traefik_username: "admin"
traefik_password: "aini"