---
# Load variables and set defaults
- name: Load common configuration
  hosts: localhost
  pre_tasks:
    - include_tasks: includes/load_vars.yml
      tags: ['always']

# Provisioning
- name: Provision Infrastructure
  hosts: provisioners
  gather_facts: true
  roles:
    - role: infrastructure/ssh_key
      tags: ssh_key
    - role: infrastructure/storage_box
      tags: storage_box
    - role: infrastructure/app_server
      tags: app_server

# Apps (including base)
- name: Manage Applications
  hosts: app_servers
  gather_facts: true
  pre_tasks:
    - include_tasks: includes/load_vars.yml
      tags: ['apps']
  tasks:
    - name: Include apps tasks
      include_tasks: includes/apps.yml
      tags: ['base','traefik','netdata','grafana','nextcloud','onlyoffice','portainer','cadvisor','librechat','nocodb', 'pgadmin', 'authelia', 'yaml.space']
