---
# Initial playbook for variable loading
- name: Load common configuration
  hosts: localhost
  pre_tasks:
    - include_tasks: includes/load_vars.yml
  vars:
    target: "{{ target | default('app') }}"
    project_defaults: "{{ playbook_dir }}/../defaults/main.yml"
    action: "{{ action | default('create') }}"  # Can be 'create' or 'delete'

# Import other playbooks
- import_playbook: provision/ssh_key.yml
  vars:
    state: "{{ 'present' if action == 'create' else 'absent' }}"
  tags: ['provision', 'ssh_key']

- import_playbook: provision/app_servers.yml
  vars:
    state: "{{ 'present' if action == 'create' else 'absent' }}"
    target: "{{ target | default('app') }}"
  tags: ['provision', 'servers', 'app']

- import_playbook: provision/gpu_servers.yml
  vars:
    state: "{{ 'present' if action == 'create' else 'absent' }}"
    target: "{{ target | default('gpu') }}"
  tags: ['provision', 'servers', 'gpu']

# Wait for server playbook
# - name: Wait for server
#   hosts: localhost
#   tasks:
#     - name: Wait for server to be ready
#       wait_for:
#         host: "[{{ hostvars[groups[target + '_servers'][0]]['ansible_host'] }}]"
#         port: 22
#         timeout: 300
#       tags: ['configure', 'servers', 'app']
#       when: action == 'create'

# configuration playbooks
- import_playbook: configure/base.yml
  vars:
    state: "{{ 'present' if action == 'create' else 'absent' }}"
    target: "{{ target | default('app') }}"
  tags: ['configure', 'base']

# - import_playbook: configure/apps.yml
#   when: action == 'create' and target == 'app'
#   tags: ['configure', 'apps']

# - import_playbook: configure/ml.yml
#   when: action == 'create' and target == 'gpu'
#   tags: ['configure', 'ml']