---
# Load variables and set defaults
- name: Load common configuration
  hosts: localhost
  pre_tasks:
    - include_tasks: includes/load_vars.yml
      tags: ['always']

  vars:
    action: "{{ action | default('create') }}"

# Provisioning
- name: Provision Infrastructure
  hosts: localhost
  gather_facts: true
  roles:
    - role: infrastructure/ssh_key
    - role: infrastructure/app_server
      tags: ['provision', 'server']

# Apps
- name: Manage Applications
  hosts: app_servers
  gather_facts: true
  tags: ['apps', 'never']
  pre_tasks:
    - include_tasks: includes/load_vars.yml
      tags: ['always']
  tasks:
    - name: Include apps tasks
      include_tasks: includes/apps.yml
      tags: ['apps']
