---
# Load variables and set defaults
- name: Load common configuration
  hosts: provisioners
  pre_tasks:
    - include_tasks: includes/load_vars.yml
      tags: ['always']

# Provisioning
- name: Provision Infrastructure
  hosts: provisioners
  gather_facts: true
  roles:
    - role: infrastructure/ssh_key
      tags: ssh_key
    - role: infrastructure/storage_box
      tags: storage_box
    - role: infrastructure/app_server
      tags: app_server
