# ansible/playbooks/ssh_key.yml
---
- name: Manage Hetzner SSH Keys
  hosts: localhost
  gather_facts: false
  vars:
    env_file: "{{ playbook_dir }}/../.env"
    project_defaults: "{{ playbook_dir }}/../defaults/main.yml"
    ssh_action: "{{ action | default('create') }}"

  pre_tasks:
    - name: Include project defaults
      include_vars:
        file: "{{ project_defaults }}"

  roles:
    - role: common/env_loader
    - role: hetzner/ssh_key