# ansible/playbooks/operations/start_server.yml
---
- name: Manage cloud server
  hosts: localhost
  gather_facts: false
  vars:
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
    server_name: "***REMOVED***-{{ target }}"
    server_type: "{{ lookup('env', 'APP_SERVER_TYPE') if target == 'app' else lookup('env', 'GPU_SERVER_TYPE') }}"
    image: "ubuntu-22.04"
    location: "fsn1"
    ssh_keys: ["{{ lookup('env', 'HETZNER_SSH_KEY_NAME') }}"]

  tasks:
    - name: Debug variables
      debug:
        msg: 
          - "Server name: {{ server_name }}"
          - "Server type: {{ server_type }}"
          - "Token exists: {{ hcloud_token != '' }}"
          - "SSH key name: {{ ssh_keys[0] }}"

    - name: Create Hetzner server
      hetzner.hcloud.hcloud_server:
        api_token: "{{ hcloud_token }}"
        name: "{{ server_name }}"
        server_type: "{{ server_type }}"
        image: "{{ image }}"
        location: "{{ location }}"
        ssh_keys: "{{ ssh_keys }}"
        state: present
      register: server

    - name: Wait for server to be ready
      wait_for:
        host: "{{ server.hcloud_server.ipv4_address }}"
        port: 22
        timeout: 300

    - name: Add server to runtime inventory
      add_host:
        name: "{{ server.hcloud_server.ipv4_address }}"
        groups: 
          - new_servers
          - "{{ target }}_servers"

    - name: Save server to inventory file
      lineinfile:
        path: "{{ playbook_dir }}/../inventory/{{ target }}_servers.ini"
        line: "{{ server.hcloud_server.ipv4_address }} server_name={{ server_name }}"
        create: yes

    - name: Configure app server
      include_tasks: ../deploy_app_server.yml
      when: target == "app"