---
- name: Configure Base System
  hosts: "{{ target }}_servers"
  become: true
  pre_tasks:
    - include_tasks: ../includes/load_vars.yml

  tasks:
    - name: Enable IPv6 in sysctl
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.forwarding
        - net.ipv6.conf.default.forwarding

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic packages
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
          - ufw
          - fail2ban
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Configure Docker daemon for IPv6
      copy:
        content: |
          {
            "ipv6": true,
            "fixed-cidr-v6": "2001:db8:1::/64",
            "experimental": true,
            "ip6tables": true
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
      notify: Restart Docker

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Configure UFW defaults
      ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: incoming, policy: deny }
        - { direction: outgoing, policy: allow }

    - name: Allow SSH through UFW (IPv4 & IPv6)
      ufw:
        rule: allow
        port: 22
        proto: tcp
        ipv6: yes

    - name: Allow HTTP through UFW (IPv4 & IPv6)
      ufw:
        rule: allow
        port: 80
        proto: tcp
        ipv6: yes

    - name: Allow HTTPS through UFW (IPv4 & IPv6)
      ufw:
        rule: allow
        port: 443
        proto: tcp
        ipv6: yes

    - name: Enable UFW
      ufw:
        state: enabled

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
