# ansible/playbooks/provision/app_servers.yml
---

- name: Provision Application Server
  hosts: localhost
  pre_tasks:
    - include_tasks: ../includes/load_vars.yml
  vars:
    state: "{{ state | default('present') }}"

  tasks:
    - name: Manage server
      hcloud_server:
        api_token: "{{ hetzner_token }}"
        name: "{{ project_name }}-app"
        server_type: "{{ app_server_type }}"
        image: "{{ server_image }}"
        location: "{{ server_location }}"
        ssh_keys:
          - "{{ hetzner_ssh_key_name }}"
        state: "{{ state }}"
        enable_ipv4: "{{ enable_ipv4 }}"
        enable_ipv6: "{{ enable_ipv6 }}"
      register: server

    - name: Add host to inventory
      add_host:
        name: "{{ server.hcloud_server.name }}"
        ansible_host: "{{ server.hcloud_server.ipv4_address }}"
        ansible_python_interpreter: /usr/bin/python3
        groups: app_servers
      when: state == "present"

    - name: Update inventory file
      lineinfile:
        path: "../../inventory/hosts"
        line: "{{ server.hcloud_server.name }} ansible_host={{ server.hcloud_server.ipv4_address }} ansible_user=root"
        regexp: "^{{ server.hcloud_server.name }} ansible_host="
        create: yes
      delegate_to: localhost
      when: state == "present"

    - name: Ensure app_servers group exists in inventory
      lineinfile:
        path: "../../inventory/hosts"
        line: "[app_servers]"
        insertbefore: BOF
        create: yes
      delegate_to: localhost
      when: state == "present"

    # Remove from inventory when deleting
    - name: Remove from inventory file
      lineinfile:
        path: "../../inventory/hosts"
        regexp: "^{{ project_name }}-app ansible_host="
        state: absent
      delegate_to: localhost
      when: state == "absent"