# ansible/playbooks/configure/ssh_key.yml
---
- name: Configure SSH Keys
  hosts: localhost
  pre_tasks:
    - include_tasks: ../includes/load_vars.yml

  tasks:
    - name: Debug environment variables
      debug:
        msg: "{{ ansible_env }}"

    - name: Read SSH public key
      ansible.builtin.slurp:
        src: "~/.ssh/id_ed25519.pub"
      register: ssh_key_content

    - name: Create SSH key in Hetzner
      hcloud_ssh_key:
        api_token: "{{ hetzner_token }}"
        name: "{{ hetzner_ssh_key_name }}"
        public_key: "{{ ssh_key_content.content | b64decode }}"
        state: present