# ansible/roles/common/traefik/tasks/main.yml
---
- name: Create Traefik directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/traefik
    - /opt/traefik/config
    - /opt/traefik/config/dynamic
    - /opt/traefik/certs

- name: Verify domain is available
  assert:
    that:
      - domain is defined
      - domain | length > 0
    fail_msg: "domain is required for Traefik management"

- name: Template docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    mode: '0644'

- name: Template Traefik configuration
  template:
    src: "{{ item.src }}"
    dest: "/opt/traefik/config/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: traefik.yml.j2, dest: traefik.yml }
    - { src: dynamic/middlewares.yml.j2, dest: dynamic/middlewares.yml }
    - { src: dynamic/tls.yml.j2, dest: dynamic/tls.yml }
    - { src: dynamic/services.yml.j2, dest: dynamic/services.yml }

- name: Create acme.json
  file:
    path: /opt/traefik/certs/acme.json
    state: touch
    mode: '0600'

- name: Create Traefik network
  community.docker.docker_network:
    name: traefik-public
    driver: bridge

- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
    pull: "missing"
    remove_orphans: true
    recreate: always
  register: traefik_output

- name: Verify traefik_output is available
  assert:
    that:
      - traefik_output is defined
      - traefik_output | length > 0
    fail_msg: "traefik_output did not come up!"
