# ansible/roles/hetzner/server/tasks/create.yml
---
- name: Validate required variables
  assert:
    that:
      - server_name is defined
      - server_type is defined
      - image is defined
      - location is defined
    fail_msg: "Missing required variables for server creation"

- name: Check if server already exists
  hcloud_server_info:
    name: "{{ server_name }}"
  register: server_info

- name: Create server if it doesn't exist
  hcloud_server:
    name: "{{ server_name }}"
    server_type: "{{ server_type }}"
    image: "{{ image }}"
    location: "{{ location }}"
    state: present
    labels:
      project: "{{ project_name }}"
      role: "{{ target }}"
  register: server_result
  when: server_info.hcloud_server_info | length == 0

- name: Wait for server to be ready
  wait_for:
    host: "{{ server_result.hcloud_server.ipv4_address }}"
    port: 22
    timeout: 300
  when: server_result is changed

- name: Add server to inventory
  add_host:
    name: "{{ server_name }}"
    groups: "{{ target }}"
    ansible_host: "{{ server_result.hcloud_server.ipv4_address }}"
  when: server_result is changed

- name: Log server creation
  debug:
    msg: "Server {{ server_name }} created successfully with IP {{ server_result.hcloud_server.ipv4_address }}"
  when: server_result is changed