# ansible/roles/hetzner/server/tasks/create.yml
---
- name: Verify required variables
  assert:
    that:
      - hcloud_token != ""
      - server_type != ""
      - target is defined
    fail_msg: "Missing required variables. Ensure HCLOUD_TOKEN and *_SERVER_TYPE are set"

- name: Create Hetzner server
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
    server_type: "{{ server_type }}"
    image: "{{ image }}"
    location: "{{ location }}"
    ssh_keys: "{{ ssh_keys }}"
    state: present
  register: server

- name: Wait for server to be ready
  wait_for:
    host: "{{ server.hcloud_server.ipv4_address }}"
    port: 22
    timeout: 300
  when: server.changed

- name: Add server to inventory
  add_host:
    name: "{{ server.hcloud_server.ipv4_address }}"
    groups: ["{{ target }}_servers"]
    ansible_user: root
    server_name: "{{ server_name }}"
  when: server.changed

- name: Save server to inventory file
  copy:
    content: |
      [{{ target }}_servers]
      {{ server.hcloud_server.ipv4_address }} ansible_user=root server_name={{ server_name }}
    dest: "{{ playbook_dir }}/../inventory/{{ target }}_servers.ini"
    mode: '0644'
  when: server.changed