# ansible/roles/hetzner/server/tasks/delete.yml
---
- name: Validate server name
  assert:
    that: server_name is defined
    fail_msg: "Server name must be provided for deletion"

- name: Debug server name
  debug:
    msg: "Destroying server: {{ server_name }}"

- name: Delete Hetzner server
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
    state: absent
  register: delete_result

- name: Remove server from inventory file
  lineinfile:
    path: "{{ playbook_dir }}/../inventory/{{ target }}_servers.ini"
    regexp: ".*server_name={{ server_name }}.*"
    state: absent
  ignore_errors: yes

- name: Log server deletion
  debug:
    msg: "Server {{ server_name }} deleted successfully"
  when: delete_result is changed
