# ansible/roles/hetzner/server/tasks/delete.yml
---
- name: Debug server name
  debug:
    msg: "Destroying server: {{ server_name }}"

- name: Delete Hetzner server
  hetzner.hcloud.hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ server_name }}"
    state: absent
  register: server

- name: Remove server from inventory file
  lineinfile:
    path: "{{ playbook_dir }}/../inventory/{{ target }}_servers.ini"
    regexp: ".*server_name={{ server_name }}.*"
    state: absent
  ignore_errors: yes