---
grafana_version: "latest"
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: "{{ vault_grafana_admin_password }}"  # Should be in vault
grafana_install_plugins: []  # List of plugins to install 